; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
name = gaitSpeed-mainBoard
default_envs = stm32f103

[env:stm32f103]
platform = ststm32
board = genericSTM32F103RC
board_build.mcu = stm32f103rct6
board_build.f_cpu = 72000000L
upload_protocol = stlink
monitor_speed = 115200
framework = arduino
lib_deps =
    stm32duino/STM32duino FreeRTOS@^10.3.3
    adafruit/Adafruit ILI9341@^1.6.3
    adafruit/Adafruit GFX Library@^1.12.5
    adafruit/Adafruit TouchScreen@^1.1.6
build_flags =
    -D NODE_ID=0x01
    -D MASTER_DISPLAY_ID=0x01
    -D HAL_CAN_MODULE_ENABLED

[env:native]
platform = native
test_framework = unity
build_flags =
    -I include
    -std=c++17
